apiVersion: v1
kind: Service
metadata:
  name: teto-api
  namespace: teto
  labels:
    app: teto-api
spec:
  selector:
    app: teto-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
